arm-elf-ld.exe -i -nostdlib -o "INTEGRATOR_DR_ARM5lnk.o" "C:\Program Files (x86)\Schneider Electric\Unity EFB Toolkit\SDKC\Config\jumptable_ARM5.o" "INTEGRATOR_DR_ARM5gnu.o"
arm-elf-ld.exe -i -T "C:\Program Files (x86)\Schneider Electric\Unity EFB Toolkit\SDKC\Tools\GnuArm5\mergescript.txt" -o "INTEGRATOR_DR_ARM5mrg.o" "INTEGRATOR_DR_ARM5lnk.o"
arm-elf-objcopy.exe --redefine-sym _$$PROG=_INTEGRATOR_DR "INTEGRATOR_DR_ARM5mrg.o"
arm-elf-objcopy.exe --add-section .note="C:\Program Files (x86)\Schneider Electric\Unity EFB Toolkit\SDKC\Tools\GnuArm5\rtsection.bin" "INTEGRATOR_DR_ARM5mrg.o"
arm-elf-objcopy.exe --strip-debug "INTEGRATOR_DR_ARM5mrg.o"
MPLink.exe /LINK "INTEGRATOR_DR_ARM5mrg.o" "INTEGRATOR_DR_ARM5.o"
MPLink.exe /LABEL:_xxNcllbk_=_xxNINTEGRATOR_DR_,_xxOcllbk_=_xxOINTEGRATOR_DR_,cllbk_=INTEGRATOR_DR_,CCF_=_Patch3Double_EXT_CCF_ "INTEGRATOR_DR_ARM5.o"
MPLink.exe /DEL=SystemEntryPoint,LanguageEntryPoint "INTEGRATOR_DR_ARM5.o"
MPLink.exe /VERIFY "INTEGRATOR_DR_ARM5.o"
MPLink.exe /VERIFY:No_PC24=_Patch3Double_EXT_CCF_ "INTEGRATOR_DR_ARM5.o"
MPLink.exe /VERIFY:Sym_ABS32 "INTEGRATOR_DR_ARM5.o"
