arm-elf-ld.exe -i -T "C:\Program Files (x86)\Schneider Electric\Unity EFB Toolkit\SDKC\Tools\GnuArm5\mergescript.txt" -o "DWORD_AS_BIT_ARM5mrg.o" "DWORD_AS_BIT_ARM5gnu.o"
arm-elf-objcopy.exe --redefine-sym DWORD_AS_BIT=_DWORD_AS_BIT "DWORD_AS_BIT_ARM5mrg.o"
arm-elf-objcopy.exe --add-section .note="C:\Program Files (x86)\Schneider Electric\Unity EFB Toolkit\SDKC\Tools\GnuArm5\rtsection.bin" "DWORD_AS_BIT_ARM5mrg.o"
arm-elf-objcopy.exe --strip-debug "DWORD_AS_BIT_ARM5mrg.o"
MPLink.exe /LINK "DWORD_AS_BIT_ARM5mrg.o" "DWORD_AS_BIT_ARM5.o"
MPLink.exe /LABEL:_xxNcllbk_=_xxNDWORD_AS_BIT_,_xxOcllbk_=_xxODWORD_AS_BIT_,cllbk_=DWORD_AS_BIT_,CCF_=_Patch1Support_CCF_ "DWORD_AS_BIT_ARM5.o"
MPLink.exe /VERIFY "DWORD_AS_BIT_ARM5.o"
MPLink.exe /VERIFY:No_PC24=_Patch1Support_CCF_ "DWORD_AS_BIT_ARM5.o"
MPLink.exe /VERIFY:Sym_ABS32 "DWORD_AS_BIT_ARM5.o"
